# --- Variables ---
$mainMod = SUPER

# --- Modular Config ---
source = ~/.config/hypr/colors/color_var.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/decorations.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/autostart.conf

general {
    border_size = 3
    col.active_border = $accent
    col.inactive_border = rgba(595959aa)
    gaps_in = 5
    gaps_out = 10
    layout = dwindle
    resize_on_border = true
}

