# --- Autostart ---
exec-once = swww-daemon
exec-once = swayosd-server
exec-once = ~/.config/hypr/scripts/wallpaper_rotator.sh

# --- Fonts (Apply to GTK) ---
exec-once = gsettings set org.gnome.desktop.interface font-name 'JetBrainsMono Nerd Font 11'
exec-once = gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrainsMono Nerd Font 10'