


# --- Decoration & Blur ---
decoration {
    rounding = 16
    active_opacity = 0.9
    inactive_opacity = 0.85
    
    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
        ignore_opacity = false
    }
}
