# --- Application Keybindings ---
bind = $mainMod, W, exec, google-chrome-stable
bind = $mainMod, T, exec, kitty
bind = $mainMod, C, exec, code
bind = $mainMod, S, exec, spotify
bind = $mainMod, E, exec, thunar
bind = $mainMod, B, exec, ~/.config/hypr/scripts/wallpaper_random.sh
bind = $mainMod, Q, killactive, 
bind = $mainMod, A, togglefloating, 
bind = SUPER, M, exec, ~/.config/hypr/scripts/power_menu.sh

# This triggers wofi when you press and release the Super key
# Toggle Wofi: If open, kill it; if closed, launch it
bindr = $mainMod, SUPER_L, exec, pkill wofi || wofi --show drun --style ~/.config/wofi/style.css

# --- Utility & System ---
bind = , F12, exec, ~/.config/hypr/scripts/toggle_nmtui.sh

# --- Audio Control ---
binde = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
binde = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bind = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

# --- Brightness Control ---
binde = , XF86MonBrightnessUp, exec, swayosd-client --brightness raise
binde = , XF86MonBrightnessDown, exec, swayosd-client --brightness lower

# --- AceBar Toggle ($mainMod + 0) ---
bind = $mainMod, 0, exec, pkill -USR1 -f ace_bar.py

# --- Screenshots (Grim/Slurp) ---
# bind = , Print, exec, grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png
bind = , Print, exec, ~/.config/hypr/scripts/screenshot.sh
# --- Workspace Navigation ---
bind = $mainMod, 1, exec, ~/.config/hypr/scripts/switch_workspace.sh 1
bind = $mainMod, 2, exec, ~/.config/hypr/scripts/switch_workspace.sh 2
bind = $mainMod, 3, exec, ~/.config/hypr/scripts/switch_workspace.sh 3
bind = $mainMod, 4, exec, ~/.config/hypr/scripts/switch_workspace.sh 4
bind = $mainMod, 5, exec, ~/.config/hypr/scripts/switch_workspace.sh 5
bind = $mainMod, 6, exec, ~/.config/hypr/scripts/switch_workspace.sh 6
bind = $mainMod, 7, exec, ~/.config/hypr/scripts/switch_workspace.sh 7
bind = $mainMod, 8, exec, ~/.config/hypr/scripts/switch_workspace.sh 8
bind = $mainMod, 9, exec, ~/.config/hypr/scripts/switch_workspace.sh 9
# bind = $mainMod, 0, exec, ~/.config/hypr/scripts/switch_workspace.sh 10

# --- Move Windows to Workspaces ---
bind = $mainMod SHIFT, 1, exec, ~/.config/hypr/scripts/move_to_workspace.sh 1
bind = $mainMod SHIFT, 2, exec, ~/.config/hypr/scripts/move_to_workspace.sh 2
bind = $mainMod SHIFT, 3, exec, ~/.config/hypr/scripts/move_to_workspace.sh 3
bind = $mainMod SHIFT, 4, exec, ~/.config/hypr/scripts/move_to_workspace.sh 4
bind = $mainMod SHIFT, 5, exec, ~/.config/hypr/scripts/move_to_workspace.sh 5
bind = $mainMod SHIFT, 6, exec, ~/.config/hypr/scripts/move_to_workspace.sh 6
bind = $mainMod SHIFT, 7, exec, ~/.config/hypr/scripts/move_to_workspace.sh 7
bind = $mainMod SHIFT, 8, exec, ~/.config/hypr/scripts/move_to_workspace.sh 8
bind = $mainMod SHIFT, 9, exec, ~/.config/hypr/scripts/move_to_workspace.sh 9
bind = $mainMod SHIFT, 0, exec, ~/.config/hypr/scripts/move_to_workspace.sh 10
